# Generated by Django 2.2 on 2020-10-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20201019_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(max_length=50, verbose_name='主机名'),
        ),
    ]
